version: '3.8'

services:
  php:
    build: .
    container_name: apple-pay-php
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    stdin_open: true
    command: tail -f /dev/null

  test:
    build: .
    container_name: apple-pay-test
    volumes:
      - .:/app
    working_dir: /app
    command: vendor/bin/phpunit
    depends_on:
      - php
